name: 'dbt_omop_dqm'
version: '0.1.0'
config-version: 2
profile: 'default'

macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

# Disable tests by default
tests:
  dbt_omop_dqm:
    +enabled: false