[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dqm-dashboard"
version = "0.1.0"
description = "Package to parse,transform and visualise dqm using Streamlit"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "psycopg[binary,pool]>=3.2.6",
    "pytest>=8.3.5",
    "streamlit>=1.44.1",
]

[project.scripts]
parse-artifacts = "dqm_dashboard.parse_dbt_artifacts:main"
transform-artifacts = "dqm_dashboard.transform_run_results:main"
streamlit-dashboard = "dqm_dashboard.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/dqm_dashboard"]

[tool.hatch.build.targets.wheel.shared-data]
"src/dqm_dashboard/static" = "static"

[tool.hatch.build]
include = ["static/"]
